apiVersion: v1
data:
  gocalc.conf: |
    server {
      listen 80 default_server;

      server_name gocalc;

      location / {
        proxy_pass http://127.0.0.1:8080;
      }
    }
kind: ConfigMap
metadata:
  name: {{ include "goappConf" . }}
  namespace: {{ include "namespace" . }}

